name: setx-cookbook
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - xarray
  - netcdf4
  - h5netcdf
  - zarr
  - cftime
  - cartopy
  - pandas
  - plotly
  - ipywidgets
  - anywidget
  - geopandas
  - dash
  - numpy
